# Generated by Django 5.0.7 on 2024-12-23 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccbb_backend', '0029_alter_cycle_asignee_alter_pastcycle_asignee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='abc_code_path',
            new_name='plant',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='path',
            new_name='plant_warehouse',
        ),
    ]
