server_tokens             off;

server {
    listen 80;
    server_name _;

    location / {
        index index.html;
        alias /app/dist/;
        try_files $uri $uri/ /index.html =404;
    }
    location /db/ {
        proxy_pass https://invapp-backend.internal.happydesert-37a62075.centralus.azurecontainerapps.io/db/;
        proxy_ssl_server_name on;
        proxy_http_version 1.1;
    }
    location /static {
        autoindex on;
        alias /app/staticfiles/;
    }
    location /E10/api/v1/ {
        proxy_pass https://12.232.138.142/E10/api/v1/;
        proxy_ssl_server_name on;
        proxy_http_version 1.1;
    }
}
