server_tokens             off;

server {
    listen                 80 default_server;
    return                  444;
}

server {
    listen 80;

    server_name .cyclecount.app;

    location / {
        index index.html;
        alias /app/dist/;
        try_files $uri $uri/ /index.html =404;
    }
}
